### PR TITLE
Add logging config

### PR DESCRIPTION
**Pull request by n-s-f**

### CODE REVIEW

**Comment by n-s-f** [comment]
#5

**Comment by schrockn** [comment]
Hey Noam! Thanks for the super fast pull request this is great.

My question is more about what is idiomatic in python. I think the idea of creating dynamic loggers on a per-graph might kind of "break" the way that logging is supposed to be used. I think typically libraries provide loggers with static names. That way an informed consumer can grab that logger out of the magical logger namespace, clear out handlers, add their own formatters and handlers, etc.

I would suggest instead just putting the name of the graph in the text of the log message by convention. However I'm relatively new to this python logging stuff so I could be under the wrong impression.

**Comment by n-s-f** [comment]
I think you might be right about general usage.

My thinking is along these lines. Let's say I want to write logs to disk for one graph and not for another. Under your suggestion I'd need a specialized handler for that, which is burdensome. Under this pull request, I have the option of per-graph configuration through specifying the name.

On the other hand, if I don't care about graphs with different logging configurations, I leave the name as the default and everything gets logged to the same loggers ('taskmap-worker' and 'taskmap-manager'). So unless I go out of my way to specify a name for the graph, the behavior is defaults to what you mention.

In either case though it's perfectly possible to grab and manipulate the loggers.

**Comment by schrockn** [comment]
Cools sounds good to me. Just wanted to flag as possible issue but it sounds like you've thought about it.

And to clear I applaud your desire to make logging more explicit and configurable on a per-instance basis. The magical global state logging style in python messes with my head a bit.

Should the logging level by configurable in def setup_loggers(config)?

It looks like it is hardcoded to DEBUG right now. This seems like the type of thing that should be in the config dict.

**Comment by n-s-f** [comment]
That sounds like a great idea. I'm not going to be able to look at this again for a few days, but feel free to add other logging configuration options to this pull request.

**Comment by schrockn** [comment]
https://github.com/n-s-f/taskmap/pull/8

**Comment by n-s-f** [comment]
Thanks!

**Pull request merged**
